---
- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: true
      
- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
      
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
      